name: Reusable workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Generate CV
        run: |
          ./run.sh --tex-only

      - name: Compile LaTeX document
        if: runner.os == 'Linux'
        uses: xu-cheng/latex-action@v4
        with:
          root_file: output/output.tex
          work_in_root_file_dir: true
          os: alpine

      - name: Upload CV PDF as an artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf-${{ inputs.os }}
          path: output/output.pdf
